name: goalie
description: A Flutter Goal and Task tracking app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  line_icons: ^2.0.1
  get:
  sqflite:
  shared_preferences:
  animate_do:
  flutter_staggered_grid_view:
  google_fonts:
  get_storage: ^2.0.3
  intl: ^0.17.0
  implicitly_animated_reorderable_list_2: ^0.5.1
  animated_progress_bar:
    git: https://github.com/Vidhanth/animated_progress_bar.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
